resources:
  pipelines:
    - name: MyWonderkidScoutingPipeline
      source:
        - provider: GitHub
          repository: github-username/football-wonderkid-scouting-app
      stages:
        - name: Build
          actions:
            - provider: CodeBuild
              input_artifacts: SourceOutput
              output_artifacts: BuildOutput
              configuration:
                ProjectName: MyWonderkidBuild
        - name: Deploy
          actions:
            - provider: CloudFormation
              input_artifacts: BuildOutput
              configuration:
                StackName: MyWonderkidScoutingAppStack
                ActionMode: CREATE_UPDATE
